"""add matching_units

Revision ID: 3dce2ced9612
Revises: d9cb7a65d2d5
Create Date: 2025-02-18 19:52:31.355082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dce2ced9612'
down_revision: Union[str, None] = 'd9cb7a65d2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_units',
    sa.Column('matching_unit_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parsing_result_id', sa.UUID(), nullable=False),
    sa.Column('matching_status', sa.String(length=50), nullable=False),
    sa.Column('trade_type', sa.String(length=50), nullable=True),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trading_party_code', sa.String(length=100), nullable=False),
    sa.Column('counterparty_code', sa.String(length=100), nullable=False),
    sa.Column('trade_ref', sa.String(length=100), nullable=True),
    sa.Column('trade_uti', sa.String(length=255), nullable=True),
    sa.Column('settlement_rate', sa.String(length=50), nullable=True),
    sa.Column('transaction_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("matching_status IN ('unmatched', 'matched')", name='check_matching_status'),
    sa.CheckConstraint("transaction_details ? 'pay_leg' AND transaction_details ? 'receive_leg'", name='check_transaction_details_structure'),
    sa.ForeignKeyConstraint(['parsing_result_id'], ['parsing_results.parsing_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('matching_unit_id'),
    sa.UniqueConstraint('trade_uti', name='unique_trade_uti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_units')
    # ### end Alembic commands ###
