"""change entity_id to long_name_id uuid

Revision ID: 6c5cf0c1718e
Revises: a8c61c3d5b8b
Create Date: 2025-02-14 23:35:05.412340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5cf0c1718e'
down_revision: Union[str, None] = 'a8c61c3d5b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_names', sa.Column('long_name_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.drop_column('entity_names', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_names', sa.Column('entity_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('entity_names', 'long_name_id')
    # ### end Alembic commands ###
