"""add entity_names table

Revision ID: a8c61c3d5b8b
Revises: d08fda4b3ea8
Create Date: 2025-02-14 23:30:18.356444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c61c3d5b8b'
down_revision: Union[str, None] = 'd08fda4b3ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_names',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('long_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_names')
    # ### end Alembic commands ###
