"""description of changes

Revision ID: cffe6f9fd722
Revises: d255ebaad80d
Create Date: 2025-02-18 19:38:29.241811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cffe6f9fd722'
down_revision: Union[str, None] = 'd255ebaad80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_names',
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('long_name_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.UniqueConstraint('long_name', name='entity_names_long_name_key')
    )
    # ### end Alembic commands ###
