"""add part_codes

Revision ID: d9cb7a65d2d5
Revises: cffe6f9fd722
Create Date: 2025-02-18 19:45:14.324341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cb7a65d2d5'
down_revision: Union[str, None] = 'cffe6f9fd722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_codes',
    sa.Column('party_code_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('party_code', sa.String(length=100), nullable=False),
    sa.Column('msger_name', sa.String(length=255), nullable=False),
    sa.Column('msger_address', sa.Text(), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('party_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('party_code_id'),
    sa.UniqueConstraint('msger_name', 'party_name', 'party_role', name='unique_party_combination'),
    sa.UniqueConstraint('party_code', name='unique_party_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_codes')
    # ### end Alembic commands ###
